# Generated by Django 3.2.2 on 2021-05-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_PostgreSQL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinicaPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePaciente', models.CharField(max_length=150)),
                ('tipoSangre', models.CharField(max_length=15)),
                ('fechaExamenMedico', models.CharField(max_length=10)),
                ('resultadoPrueba', models.CharField(max_length=50)),
                ('enfermedadesImportantes', models.CharField(max_length=150)),
                ('medicamentoActual', models.CharField(max_length=100)),
                ('enfermedadesCronicas', models.CharField(max_length=150)),
                ('alergias', models.CharField(max_length=100)),
                ('enfermedadesCronicasFamiliares', models.CharField(max_length=100)),
            ],
        ),
    ]
