# Generated by Django 3.2.2 on 2021-06-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_PostgreSQL', '0002_historialclinicapacientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMedicamento', models.CharField(max_length=30)),
                ('costo', models.CharField(max_length=18)),
                ('piezas', models.CharField(max_length=18)),
            ],
        ),
    ]
