# Generated by Django 3.2.2 on 2021-06-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_PostgreSQL', '0003_medicamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('curp', models.CharField(max_length=18)),
                ('correo', models.CharField(max_length=50)),
                ('fechaAtencion', models.CharField(max_length=10)),
                ('horaAtencion', models.CharField(max_length=10)),
            ],
        ),
    ]
