# Generated by Django 3.2.2 on 2021-06-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_PostgreSQL', '0004_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notamedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechadeatencion', models.CharField(max_length=18)),
                ('nombre', models.CharField(max_length=120)),
                ('emailpaciente', models.CharField(max_length=120)),
                ('subjetivo', models.CharField(max_length=1000)),
                ('objetivo', models.CharField(max_length=1000)),
                ('analisis', models.CharField(max_length=1000)),
                ('plan', models.CharField(max_length=1000)),
            ],
        ),
    ]
